#This playbook is suitable form Amazon Linux server 
---
- name: Deploy SSL Certificate
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3 
  

  tasks:

    - name: ensure pip installed 
      package:
       name: python3-pip
       state: present

    - name: Install boto, boto3 and botocore
      pip:
         name: "{{ item }}"
      loop:
        - boto
        - boto3
        - botocore

    - name: Check if Apache installed 
      become: true 
      command: rpm -q httpd
      register: apache_installed
      failed_when: false
      changed_when: false

    - name: Install Apache if not installed
      become: true
      package:
        name: httpd
        state: present
      when: "'not installed' in apache_installed.stdout"
      #notify: Start Apache service

  #handlers:
    - name: Start Apache service
      become: true
      service:
        name: httpd
        state: started

    - name: Check File1 Exist or not 
      stat:
       path: "/home/ec2-user/file1.txt"
      register: file1_status

    - name: Display If File1 exist 
      debug: 
        msg: "file1_exist"
      when: file1_status.stat.exists

    - name: Create File1 if not exist 
      file:
       path: "/home/ec2-user/file1.txt"
       state: touch 
      when: not file1_status.stat.exists

    - name: Fetch the Values from AWS SSM Parameter 
      set_fact:
       ssm_parameter_value: "{{ lookup('amazon.aws.aws_ssm', 'Test_name', region='ap-south-1' ) }}"

    - name: Copy SSM Parameter values into File1 
      copy:
       content: "{{ ssm_parameter_value }}"
       dest: /home/ec2-user/file1.txt 

    - name: Restart apache service
      become: true
      service:
        name: httpd
        state: restarted
